services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    Model\Mapper\GetDataMapper:
        factory: Component\MapperFactory:create
        arguments:
            - 'Model\Mapper\GetDataMapper'
   
   
          
        
